plugin:
    name: 'logingrupa.stylebookshopaholic::lang.plugin.name'
    description: 'logingrupa.stylebookshopaholic::lang.plugin.description'
    author: Logingrupa
    icon: icon-smile-o
    homepage: ''
permissions:
    stylebookshopaholic-menu-ideas:
        label: 'logingrupa.stylebookshopaholic::lang.permission.idea'
        tab: 'logingrupa.stylebookshopaholic::lang.tab.permissions'
