offer:
  label: 'lovata.shopaholic::lang.offer.name'
  manage:
    list: $/lovata/shopaholic/models/offer/columns.yaml
    form: $/lovata/shopaholic/models/offer/fields.yaml
    showSearch: true
    showSorting: true
    recordsPerPage: 20
  view:
    list: $/lovata/shopaholic/models/offer/columns.yaml
    recordUrl: lovata/shopaholic/offers/update/:id
    toolbarButtons: 'link|unlink'
    showSearch: true
    showSorting: true
    recordsPerPage: 20